"""updating columns

Revision ID: 398ea1125dba
Revises: e0c07c2ed74c
Create Date: 2023-12-14 10:36:50.206328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398ea1125dba'
down_revision = 'e0c07c2ed74c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sun', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(), nullable=True))
        batch_op.drop_column('images')
        batch_op.drop_column('care_instructions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('care_instructions', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('images', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')
        batch_op.drop_column('image1')
        batch_op.drop_column('sun')
        batch_op.drop_column('water')

    # ### end Alembic commands ###
