"""converted price to string

Revision ID: 45e341859a5e
Revises: fa26d5afc7ef
Create Date: 2023-12-13 14:51:21.507325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e341859a5e'
down_revision = 'fa26d5afc7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
