"""testing qty constraint

Revision ID: 5abf03b109e9
Revises: 14cf441754c2
Create Date: 2023-12-29 11:17:02.013972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abf03b109e9'
down_revision = '14cf441754c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('qty',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('qty',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
