"""Add cascade delete to reviews

Revision ID: 9e1b82dcbf93
Revises: 16b9643286e6
Create Date: 2024-07-02 20:02:15.835521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1b82dcbf93'
down_revision = '16b9643286e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_customer_id_customers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_customer_id_customers'), 'customers', ['customer_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_customer_id_customers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_customer_id_customers', 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###
