"""foreign key

Revision ID: a6f1bb93caf7
Revises: 2b00ad6bc22b
Create Date: 2024-01-09 19:01:35.900892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f1bb93caf7'
down_revision = '2b00ad6bc22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopper_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_shopper_id_shoppers'), 'shoppers', ['shopper_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_shopper_id_shoppers'), type_='foreignkey')
        batch_op.drop_column('shopper_id')

    # ### end Alembic commands ###
