"""add cascade delete to cartitems

Revision ID: c2818527b684
Revises: 9e1b82dcbf93
Create Date: 2024-07-02 20:25:09.788628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2818527b684'
down_revision = '9e1b82dcbf93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cartitems_plant_id_plants', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cartitems_plant_id_plants'), 'plants', ['plant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartitems', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cartitems_plant_id_plants'), type_='foreignkey')
        batch_op.create_foreign_key('fk_cartitems_plant_id_plants', 'plants', ['plant_id'], ['id'])

    # ### end Alembic commands ###
